### ISSUE TITLE
DSA 4.1: Helden mit Arcanovi [Semipermanenz] werden nicht richtig importiert

### ISSUE THREAD

**Issue by DarthSpot** [nitrout/avesbot#1]
Helden, die die Sonderfertigkeit "Semipermanenz I" erlangen, bekommen einen neuen Zauber "Arcanovi [Semipermanenz]"

Importiert man einen solchen Helden, gibt AvesBot eine Fehlermeldung aus, die nicht näher spezifiziert ist.
Lädt man die Seite neu, taucht der importierte Eintrag auf, es Fehlen jedoch in der Liste der Zauber alle Einträge ab Arcanovi.

Beispiel wurde diesem Ticket beigefügt.

[TestiMcTest.zip](https://github.com/nitrout/avesbot/files/14951132/TestiMcTest.zip)

**Comment by nitrout** [comment]
Das neue Release unterstützt jetzt den Import direkt über Discord.
Das Verhalten ist jetzt etwas besser (die Zauberliste ist vollständig), allerdings werden die Varianten des Zaubers noch nicht richtig erkannt, sodass nur einer der beiden Zauber es in die Liste schafft.
Die fehlende Variante kann dann in der Website nachgetragen werden.

**Comment by nitrout** [comment]
Zaubervarianten wieder der Semipermanente Arcanovi werden jetzt richtig importiert!
Dies gilt nur für den Import über die Discord Commands!
